<?php

declare(strict_types=1);

return [
    '@Symfony' => true,
    'no_multiline_whitespace_around_double_arrow' => true,
    'no_whitespace_before_comma_in_array' => true,
    'normalize_index_brace' => true,
    'trim_array_spaces' => true,
    'whitespace_after_comma_in_array' => true,
    'no_trailing_comma_in_singleline' => true,
    'class_reference_name_casing' => true,
    'magic_constant_casing' => true,
    'magic_method_casing' => true,
    'native_function_casing' => true,
    'native_function_type_declaration_casing' => true,
    'cast_spaces' => false,
    'multiline_comment_opening_closing' => true,
    'no_empty_comment' => true,
    'no_trailing_whitespace_in_comment' => true,
    'single_line_comment_spacing' => true,
    'elseif' => true,
    'type_declaration_spaces' => true,
    'lambda_not_used_import' => true,
    'no_unused_imports' => true,
    'ordered_imports' => ['sort_algorithm' => 'alpha', 'imports_order' => ['class', 'function', 'const']],
    'single_import_per_statement' => true,
    'single_line_after_imports' => true,
    'explicit_indirect_variable' => true,
    'short_scalar_cast' => true,
    'no_short_bool_cast' => true,
    'yoda_style' => [
        'equal' => false,
        'identical' => false,
        'less_and_greater' => false,
    ],
    'no_useless_return' => true,
    'standardize_not_equals' => true,
    'no_blank_lines_after_phpdoc' => true,
    'explicit_string_variable' => true,
    'general_phpdoc_annotation_remove' => true,
    'align_multiline_comment' => ['comment_type' => 'all_multiline'],
    'no_empty_phpdoc' => true,
    'no_superfluous_phpdoc_tags' => true,
    'phpdoc_order' => true,
    'phpdoc_var_annotation_correct_order' => true,
    'types_spaces' => ['space' => 'none'],
    'phpdoc_trim' => true,
    'array_indentation' => true,
    'fully_qualified_strict_types' => true,
    'global_namespace_import' => [
        'import_classes' => true,
        'import_constants' => false,
        'import_functions' => false,
    ],
];
