sonata_admin:
    title: "Sonata Admin"
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
          sonata.admin.group.settings:
            label: Settings
            icon: 'fa fa-gear'
            items:
              - admin.user_vendor_setting
              - admin.model_profile
#          sonata.admin.group.chat:
#            label: Chat
#            icon: 'fa fa-comments'
          sonata.admin.group.internal:
            label: System
            icon: 'fa fa-wrench'
            items:
              - sonata.user.admin.user
              - admin.model
              - admin.app_setting

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.user_vendor_setting:
        class: App\Admin\VendorSettingAdmin
        arguments: ['@security.token_storage']
        tags:
            - { name: sonata.admin, model_class: App\Entity\VendorSetting, controller: App\Controller\VendorSettingAdminController, manager_type: orm, group: Settings, label: Vendor }
    admin.model:
        class: App\Admin\ModelAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Model, controller: ~, manager_type: orm, group: System, label: Model }
    admin.app_setting:
        class: App\Admin\AppSettingAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\AppSetting, controller: ~, manager_type: orm, group: admin, label: AppSetting }
    admin.model_profile:
        class: App\Admin\ModelProfileAdmin
        arguments: ['@security.token_storage', '@App\Repository\ModelRepository']
        tags:
            - { name: sonata.admin, model_class: App\Entity\ModelProfile, controller: ~, manager_type: orm, group: Settings, label: Profile }
