sonata_admin:
    title: "Sonata Admin"
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
          sonata.admin.group.settings:
            label: Settings
            icon: 'fa fa-gear'
            items:
              - admin.user_vendor_setting
          sonata.admin.group.users:
            label: Users
            icon: 'fa fa-users'
            items:
              - sonata.user.admin.user

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.user_vendor_setting:
        class: App\Admin\VendorSettingAdmin
        arguments: ['@security.token_storage']
        tags:
            - { name: sonata.admin, model_class: App\Entity\VendorSetting, controller: App\Controller\VendorSettingAdminController, manager_type: orm, group: Settings, label: Vendor }
