sonata_user:
  class:
    user: App\Entity\User
  resetting:
    email:
      address: "%env(MAILER_FROM)%"
      sender_name: Backoffice
  impersonating:
      route: sonata_admin_dashboard

  #mailer: custom.mailer.service.id
  #security_acl: true
