name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init project
      run: make init

    - name: Run tests
      run: make test

    - name: Run code analysis (phpstan)
      run: make phpstan

    - name: Check code style (csfixer)
      run: make csfix-show